import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import Navbar from "../components/navbar/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const jbMono = localFont({
  src:'../../public/fonts/JetBrainsMono-Regular.woff2',
  variable: "--font-jb-mono",
  weight: "400"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jbMono.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>


    </html>
  );
}
